### ISSUE TITLE
Prevent suggestions showing if they're identical to the current string

### ISSUE THREAD

**Issue by stevehopkinson** [NodeGroup2/autocomplete-project#64]
I.e. prevent 'k' from showing as a suggestion if the user types in 'k'

**Comment by msachi** [comment]
- Whatever is typed in is always shown as one of the suggestions (this is Google style)
- Individual letters are actually entires in the dictionary, so they will be displayed as suggestions. The dictionary is based on popularity (Google searches) so apparently people do like to search for individual letters!
