### ISSUE TITLE
Things I really like

### ISSUE THREAD

**Issue by lucymonie** [NodeGroup2/autocomplete-project#65]
- The full sentence in the suggestions drop-down is a neat touch
- It's great how the next word is in blue
- I think the way the hover turns the selection bold
- The link to google search (it's nice that it has a reason to exist!)
- I love your border-radius work, guys
- Nice favicon, clean layout and good choice of font
- Great modular and easy-to-read code in app.js

**Comment by msachi** [comment]
💕
