### ISSUE TITLE
onkeyup() method - server abuse

### ISSUE THREAD

**Issue by SavageWilliam** [NodeGroup2/autocomplete-project#78]
This method shoots a request and accepts a response on every single key. (inc. shift for ex)

You could minimise server use by limiting the keys which send a request? 

Or look at other JS events?... 'input' is a cool one to check out.

**Comment by msachi** [comment]
Fixed, thanks!

**Comment by marisid** [comment]
Changed `onkeyup` event to `oninput` as advised :smile: Thanks :+1:
