### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by lucymonie** [NodeGroup2/autocomplete-project#79]
Hard-coded ul "suggestion_list" maybe a bit limiting, but not really something to fix at this stage.

**Comment by marisid** [comment]
Thanks @lucymonie! As discussed, it's about a design decision, whether you want a fixed number of suggestions or more flexibility. And how costly it is in terms of DOM manipulation to create elements on the fly. (though maybe not that costly for our project scale :wink:)
